// This file only contains ways to reduce complexity generated by the CodeMetrics extension

// Have only one exit point.  You may be tempted to do:
// if (expression){ return true;}
// return false;
//    But instead do:
// let returnExpression = defaultReturnValue;
// if (expression) { returnExpression = newReturnValue; }
// return returnExpression;

// Reduce the number of checks in top level functions.
// if( x < 15 && x > 7 || y < 10 && y > 5) { }
//    Should be refactored to its own check
// if(isValue(x, y)) {}
// private isValid(x, y){ return  x < 15 && x > 7 || y < 10 && y > 5; }
